### ISSUE TITLE
responsive issue.!!

### ISSUE THREAD

**Issue by suriyaJaay** [nplutt/personal-website#9]
Hello nick,

thanks for posting your project.  am actually doing demo site , so i using your project as reference.

currently am facing some responsive issue. I've 11 routes when minimize the window only 3 menus in top navbar is showing rest is disappeared. 

example
-------- 
just assume below are my topnav routers
A | B | C | D | E | F | G | H | I | J | K | L

if brower minimised to mobile size am able to see A | B | C 

am not good at css and responsive topics. i tried to sort it out since last weekend. but failed. really don't know where to make changes in materiel. 

kindly help me on this. i just want this project as responsive.

hope you help me 

thank you

**Comment by nplutt** [comment]
Hey, I would advise changing the number in [this](https://github.com/nplutt/personal-website/blob/58a36ebd91cb8c3ad2a64797e1f575777e7a4a22/src/app/header/header.component.ts#L24) line to be bigger. Also I would advise against having 10+ top nav routers, if I were you I would try to combine some of those into a dropdown menu or something.
